// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceBondOutput.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ServiceBondOutput.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ServiceBondOutput_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ServiceBondOutput_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ServiceBondOutput_2eproto() {
  protobuf_AddDesc_ServiceBondOutput_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ServiceBondOutput.proto");
  GOOGLE_CHECK(file != NULL);
  ServiceBondOutput_descriptor_ = file->message_type(0);
  static const int ServiceBondOutput_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServiceBondOutput, price_),
  };
  ServiceBondOutput_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ServiceBondOutput_descriptor_,
      ServiceBondOutput::default_instance_,
      ServiceBondOutput_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServiceBondOutput, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServiceBondOutput, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ServiceBondOutput));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ServiceBondOutput_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ServiceBondOutput_descriptor_, &ServiceBondOutput::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ServiceBondOutput_2eproto() {
  delete ServiceBondOutput::default_instance_;
  delete ServiceBondOutput_reflection_;
}

void protobuf_AddDesc_ServiceBondOutput_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027ServiceBondOutput.proto\"\"\n\021ServiceBond"
    "Output\022\r\n\005price\030\001 \002(\002", 61);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ServiceBondOutput.proto", &protobuf_RegisterTypes);
  ServiceBondOutput::default_instance_ = new ServiceBondOutput();
  ServiceBondOutput::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ServiceBondOutput_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ServiceBondOutput_2eproto {
  StaticDescriptorInitializer_ServiceBondOutput_2eproto() {
    protobuf_AddDesc_ServiceBondOutput_2eproto();
  }
} static_descriptor_initializer_ServiceBondOutput_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ServiceBondOutput::kPriceFieldNumber;
#endif  // !_MSC_VER

ServiceBondOutput::ServiceBondOutput()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ServiceBondOutput)
}

void ServiceBondOutput::InitAsDefaultInstance() {
}

ServiceBondOutput::ServiceBondOutput(const ServiceBondOutput& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ServiceBondOutput)
}

void ServiceBondOutput::SharedCtor() {
  _cached_size_ = 0;
  price_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ServiceBondOutput::~ServiceBondOutput() {
  // @@protoc_insertion_point(destructor:ServiceBondOutput)
  SharedDtor();
}

void ServiceBondOutput::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ServiceBondOutput::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ServiceBondOutput::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ServiceBondOutput_descriptor_;
}

const ServiceBondOutput& ServiceBondOutput::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ServiceBondOutput_2eproto();
  return *default_instance_;
}

ServiceBondOutput* ServiceBondOutput::default_instance_ = NULL;

ServiceBondOutput* ServiceBondOutput::New() const {
  return new ServiceBondOutput;
}

void ServiceBondOutput::Clear() {
  price_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ServiceBondOutput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ServiceBondOutput)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float price = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &price_)));
          set_has_price();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ServiceBondOutput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ServiceBondOutput)
  return false;
#undef DO_
}

void ServiceBondOutput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ServiceBondOutput)
  // required float price = 1;
  if (has_price()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->price(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ServiceBondOutput)
}

::google::protobuf::uint8* ServiceBondOutput::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ServiceBondOutput)
  // required float price = 1;
  if (has_price()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->price(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ServiceBondOutput)
  return target;
}

int ServiceBondOutput::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required float price = 1;
    if (has_price()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ServiceBondOutput::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ServiceBondOutput* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ServiceBondOutput*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ServiceBondOutput::MergeFrom(const ServiceBondOutput& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_price()) {
      set_price(from.price());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ServiceBondOutput::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServiceBondOutput::CopyFrom(const ServiceBondOutput& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServiceBondOutput::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ServiceBondOutput::Swap(ServiceBondOutput* other) {
  if (other != this) {
    std::swap(price_, other->price_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ServiceBondOutput::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ServiceBondOutput_descriptor_;
  metadata.reflection = ServiceBondOutput_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
