// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServiceBondOutput.proto

#ifndef PROTOBUF_ServiceBondOutput_2eproto__INCLUDED
#define PROTOBUF_ServiceBondOutput_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ServiceBondOutput_2eproto();
void protobuf_AssignDesc_ServiceBondOutput_2eproto();
void protobuf_ShutdownFile_ServiceBondOutput_2eproto();

class ServiceBondOutput;

// ===================================================================

class ServiceBondOutput : public ::google::protobuf::Message {
 public:
  ServiceBondOutput();
  virtual ~ServiceBondOutput();

  ServiceBondOutput(const ServiceBondOutput& from);

  inline ServiceBondOutput& operator=(const ServiceBondOutput& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServiceBondOutput& default_instance();

  void Swap(ServiceBondOutput* other);

  // implements Message ----------------------------------------------

  ServiceBondOutput* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServiceBondOutput& from);
  void MergeFrom(const ServiceBondOutput& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float price = 1;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 1;
  inline float price() const;
  inline void set_price(float value);

  // @@protoc_insertion_point(class_scope:ServiceBondOutput)
 private:
  inline void set_has_price();
  inline void clear_has_price();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float price_;
  friend void  protobuf_AddDesc_ServiceBondOutput_2eproto();
  friend void protobuf_AssignDesc_ServiceBondOutput_2eproto();
  friend void protobuf_ShutdownFile_ServiceBondOutput_2eproto();

  void InitAsDefaultInstance();
  static ServiceBondOutput* default_instance_;
};
// ===================================================================


// ===================================================================

// ServiceBondOutput

// required float price = 1;
inline bool ServiceBondOutput::has_price() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServiceBondOutput::set_has_price() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServiceBondOutput::clear_has_price() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServiceBondOutput::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline float ServiceBondOutput::price() const {
  // @@protoc_insertion_point(field_get:ServiceBondOutput.price)
  return price_;
}
inline void ServiceBondOutput::set_price(float value) {
  set_has_price();
  price_ = value;
  // @@protoc_insertion_point(field_set:ServiceBondOutput.price)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServiceBondOutput_2eproto__INCLUDED
